### ISSUE TITLE
You have requested a non-existent parameter "odiseo_sylius_vendor.model.vendor.class".

### ISSUE THREAD

**Issue by aimeric** [odiseoteam/SyliusVendorPlugin#1]
Hi, 

I just tried to add your bundle to sylius but I'm getting this error:

`You have requested a non-existent parameter "odiseo_sylius_vendor.model.vendor.class".`

**AppKernel.php**

`new Odiseo\SyliusVendorPlugin\OdiseoSyliusVendorPlugin(),`

**routing.yml**

```
odiseo_sylius_admin_vendor:
   resource: "@OdiseoSyliusVendorPlugin/Resources/config/routing/admin_vendor.yml"


odiseo_sylius_shop_vendor:
    resource: "@OdiseoSyliusVendorPlugin/Resources/config/routing/shop_vendor.yml"
    prefix: /vendors
```
**config.yml**

```
    - { resource: "@OdiseoSyliusVendorPlugin/Resources/config/app/config.yml" }
    - { resource: "@OdiseoSyliusVendorPlugin/Resources/config/grids/vendor.yml" }
```

**composer.json**
`"odiseoteam/sylius-vendor-plugin": "dev-master"`

Do you have any idea how to fix this issue ?
Thank you
