### ISSUE TITLE
Can't extend plugin

### ISSUE THREAD

**Issue by alekseyp** [odiseoteam/SyliusVendorPlugin#12]
After upgrading to v1.2.4 plugin version and Sylius 1.6.4 I can't extend the plugin.

```
# config/packages/sylius/resource.yml
sylius_resource:
    resources:
        odiseo_sylius_vendor_plugin.vendor:
            classes:
                model: App\Entity\Vendor
                repository: App\Repository\VendorRepository
```

but debugger shows that it not overwritten  

```
/srv/sylius # php bin/console debug:container --parameter=odiseo_sylius_vendor_plugin.model.vendor.class
 ------------------------------------------------ -----------------------------------------
  Parameter                                        Value
 ------------------------------------------------ -----------------------------------------
  odiseo_sylius_vendor_plugin.model.vendor.class   Odiseo\SyliusVendorPlugin\Entity\Vendor
 ------------------------------------------------ -----------------------------------------

/srv/sylius # php bin/console debug:container --parameter=odiseo_sylius_vendor_plugin.repository.vendor.class
 ----------------------------------------------------- -------------------------------------------------------
  Parameter                                             Value
 ----------------------------------------------------- -------------------------------------------------------
  odiseo_sylius_vendor_plugin.repository.vendor.class   Odiseo\SyliusVendorPlugin\Repository\VendorRepository
```

```
# App\Entity\Vendor

<?php

declare(strict_types=1);

namespace App\Entity;

use Odiseo\SyliusVendorPlugin\Entity\Vendor as BaseVendor;
use Odiseo\SyliusVendorPlugin\Entity\VendorInterface;
use Odiseo\SyliusVendorPlugin\Entity\VendorTranslation;
use Odiseo\SyliusVendorPlugin\Entity\VendorTranslationInterface;

class Vendor extends BaseVendor implements VendorInterface
{
}
```

Let me know if any other info will help.
