### ISSUE TITLE
Can't extend VendorTranslation

### ISSUE THREAD

**Issue by zvitek** [odiseoteam/SyliusVendorPlugin#13]
Hello, it's possible to extend VendorTranslation with additional fields? 
I`m a new in Sylius a my standart solution doesn't work.

```php
declare(strict_types=1);
namespace App\Entity\Vendor;

use Doctrine\ORM\Mapping as ORM;
use \Odiseo\SyliusVendorPlugin\Entity\VendorTranslation as BaseVendorTranslation;

class VendorTranslation extends BaseVendorTranslation implements VendorTranslationInterface
{
    /** @ORM\Column(type="text", nullable=true) */
    private $about;

    public function getAbout(): ?string
    {
        return $this->about;
    }

    public function setAbout(string $about = null): void
    {
        $this->abou = $about;
    }
}
```
and _sylius.yaml

```
sylius_resource:
    resources:
        odiseo_sylius_vendor_plugin.vendor:
            translation:
                classes:
                    model: App\Entity\Vendor\VendorTranslation
```

Thank you for help.
