### ISSUE TITLE
Register own listeners on create/update vendor

### ISSUE THREAD

**Issue by zvitek** [odiseoteam/SyliusVendorPlugin#14]
Hello, I would like to extend you plugin for more images. Everything is ok, but I have a problem to register event listener for upload files. Is there a way how to register own listener on vendor create/update event? 
Thank you for help

**Comment by bigboss86** [comment]
Hi @zvitek. You can use the ImageUploadListener from Sylius (https://docs.sylius.com/en/latest/cookbook/images/images-on-entity.html):

```
# services.yml
services:
    app.listener.images_upload:
        class: Sylius\Bundle\CoreBundle\EventListener\ImagesUploadListener
        parent: sylius.listener.images_upload
        autowire: true
        autoconfigure: false
        public: false
        tags:
            - { name: kernel.event_listener, event: sylius.shipping_method.pre_create, method: uploadImages }
            - { name: kernel.event_listener, event: sylius.shipping_method.pre_update, method: uploadImages }
```

By the way, we already did that in our Sylius Marketplace Plugin: https://odiseo.io/plugins-and-bundles/premium/sylius-mvm-plugin

Regards.
