### ISSUE TITLE
The table with name 'sylius.odiseo_vendor' already exists.

### ISSUE THREAD

**Issue by lucassimonin** [odiseoteam/SyliusVendorPlugin#19]
Hello,

When I try to override the model with the configuration like this:

```
sylius_resource:
    resources:
        odiseo_sylius_vendor_plugin.vendor:
            classes:
                model: App\Entity\Vendor\Vendor
```

```
use Odiseo\SyliusVendorPlugin\Entity\Vendor as BaseVendor;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class Vendor
 *
 * @package App\Entity\Vendor
 * @ORM\Entity
 * @ORM\Table(name="odiseo_vendor")
 */
class Vendor extends BaseVendor
[...]
```
and when I try to update schema i got this error:
`The table with name 'sylius.odiseo_vendor' already exists. `

Can you help me ?

thank :)
